import config from "./config";

export const commands = new discord.command.CommandGroup({
  defaultPrefix: config.prefix,
});
export enum Colors {
  BLURPLE = 7506394,
}
export const timeMap = new Map([
  ["decade", 1000 * 60 * 60 * 24 * 365 * 10],
  ["year", 1000 * 60 * 60 * 24 * 365],
  ["month", 1000 * 60 * 60 * 24 * 31],
  ["week", 1000 * 60 * 60 * 24 * 7],
  ["day", 1000 * 60 * 60 * 24],
  ["hour", 1000 * 60 * 60],
  ["minute", 1000 * 60],
  ["second", 1000],
  ["millisecond", 1],
]);
export enum ChannelTypes {
  BASE = -1,
  GUILD_TEXT = 0,
  DM = 1,
  GUILD_VOICE = 2,
  GROUP_DM = 3,
  GUILD_CATEGORY = 4,
  GUILD_NEWS = 5,
  GUILD_STORE = 6,
  GUILD_NEWS_THREAD = 10,
  GUILD_PUBLIC_THREAD = 11,
  GUILD_PRIVATE_THREAD = 12,
  GUILD_STAGE_VOICE = 13,
  GUILD_DIRECTORY = 14,
}
export const ChannelTypesText: Record<ChannelTypes, string> = {
  [ChannelTypes.BASE]: "Base Channel",
  [ChannelTypes.GUILD_TEXT]: "Guild Text",
  [ChannelTypes.DM]: "Direct Message",
  [ChannelTypes.GUILD_VOICE]: "Guild Voice",
  [ChannelTypes.GROUP_DM]: "Direct Message Group",
  [ChannelTypes.GUILD_CATEGORY]: "Guild Category",
  [ChannelTypes.GUILD_NEWS]: "Guild News",
  [ChannelTypes.GUILD_STORE]: "Guild Store",
  [ChannelTypes.GUILD_NEWS_THREAD]: "Guild News Thread",
  [ChannelTypes.GUILD_PUBLIC_THREAD]: "Guild Public Thread",
  [ChannelTypes.GUILD_PRIVATE_THREAD]: "Guild Private Thread",
  [ChannelTypes.GUILD_STAGE_VOICE]: "Guild Stage Voice",
  [ChannelTypes.GUILD_DIRECTORY]: "Guild Directory",
};
export enum Statuses {
  ONLINE = "online",
  DND = "dnd",
  IDLE = "idle",
  INVISIBLE = "invisible",
  OFFLINE = "offline",
}
export const PresenceStatusColors = {
  online: 4437377,
  dnd: 15746887,
  idle: 16426522,
  offline: 7634829,
};

export const PresenceStatusTexts = {
  online: "Online",
  dnd: "Do Not Disturb",
  idle: "Idle",
  offline: "Offline",
};
export enum Locales {
  BULGARIAN = "bg",
  CHINESE = "zh-CN",
  CHINESE_TAIWAN = "zh-TW",
  CROATIAN = "hr",
  CZECH = "cs",
  DANISH = "da",
  DUTCH = "nl",
  ENGLISH_GB = "en-GB",
  ENGLISH_US = "en-US",
  FINNISH = "fi",
  FRENCH = "fr",
  GERMAN = "de",
  GREEK = "el",
  HUNGARIAN = "hu",
  ITALIAN = "it",
  JAPANESE = "ja",
  KOREAN = "ko",
  LITHUANIAN = "lt",
  NORWEGIAN = "no",
  POLISH = "pl",
  PORTUGUESE_BRAZILIAN = "pt-BR",
  ROMANIAN = "ro",
  RUSSIAN = "ru",
  SPANISH = "es-ES",
  SWEDISH = "sv-SE",
  THAI = "th",
  TURKISH = "tr",
  UKRAINIAN = "uk",
  VIETNAMESE = "vi",
}

export const LocalesText = Object.freeze({
  [Locales.BULGARIAN]: "Bulgarian",
  [Locales.CHINESE]: "Chinese, China",
  [Locales.CHINESE_TAIWAN]: "Chinese, Taiwan",
  [Locales.CROATIAN]: "Croatian",
  [Locales.CZECH]: "Czech",
  [Locales.DANISH]: "Danish",
  [Locales.DUTCH]: "Dutch",
  [Locales.ENGLISH_GB]: "English, UK",
  [Locales.ENGLISH_US]: "English, US",
  [Locales.FINNISH]: "Finnish",
  [Locales.FRENCH]: "French",
  [Locales.GERMAN]: "German",
  [Locales.GREEK]: "Greek",
  [Locales.HUNGARIAN]: "Hungarian",
  [Locales.ITALIAN]: "Italian",
  [Locales.JAPANESE]: "Japanese",
  [Locales.KOREAN]: "Korean",
  [Locales.LITHUANIAN]: "Lithuanian",
  [Locales.NORWEGIAN]: "Norwegian",
  [Locales.POLISH]: "Polish",
  [Locales.PORTUGUESE_BRAZILIAN]: "Portuguese, Brazilian",
  [Locales.ROMANIAN]: "Romanian",
  [Locales.RUSSIAN]: "Russian",
  [Locales.SPANISH]: "Spanish",
  [Locales.SWEDISH]: "Swedish",
  [Locales.THAI]: "Thai",
  [Locales.TURKISH]: "Turkish",
  [Locales.UKRAINIAN]: "Ukrainian",
  [Locales.VIETNAMESE]: "Vietnamese",
});
