# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.author.name, 'Version Bump')"
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      jobs:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install node_modules
      run: npm i
    - name: Lint js/ts
      run: npm run lint --if-present
    - name: Build Rollup
      run: npm run build --if-present
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Upload bundle
      uses: actions/upload-artifact@v2
      with:
        name: bundle.js
        path: dist/bundle.js
    - name: Publish to all guilds
      run: npm run publish --if-present
      env:
        API_TOKEN: ${{secrets.PYLON_API_KEY}}
        WEBHOOK_URL: ${{secrets.WEBHOOK_URL}}
        GITHUB: true
