# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration

on:
  push:
    paths:
      - '**.ts'
      - 'package.json'
      - 'publish.js'
      - 'rollup.config.js'
    branches:
      - master

jobs:
  modules:
    name: Install NPM Modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install node_modules
      run: npm i

  linting:
    name: Lint
    needs: modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Lint js/ts
      run: npm run lint --if-present

  build:
    name: Build Rollup
    runs-on: ubuntu-latest
    needs: linting
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Build Rollup
      run: npm run build --if-present
