name: Version Bump
on: 
  push:
    paths:
      - '**.ts'
      - 'package.json'
      - 'publish.js'
      - 'rollup.config.js'


jobs:
  testdeploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.author.name, 'Version Bump')"
#    needs: build
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name:  'Automated Version Bump'
      uses:  'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        commit-message: 'CI: bumps version to {{version}} [skip ci]'